### ISSUE TITLE
Workbench - Add IIIF Image 

### ISSUE THREAD

**Issue by IanMcCrabb** [Systemik-Solutions/glycerine-support#19]
First of all, the real problem for us is that people will have trouble to get the IIIF image URLs directly as most of publicly accessible resources are IIIF manifests. Although they can get the actual IIIF image URLs from a IIIF manifest, it is not feasible for majority of users. I think we should rethink the use of "Add IIIF Image" when people are creating an image set. We could automatically detect the type of URL people pasted in. If it is an IIIF image URL, it will add that image straightaway. If it is an IIIF manifest URL, it will prompt a list of images with preview from that manifest. People can then select the image they want and add it into the image set. Not that this is different from the "Import from manifest" function which will import the manifest information such as label and summary plus all images from the manifest.

**Comment by yangli0516** [comment]
Have changed the "Add IIIF Image" function:

- When providing an IIIF image URL, it adds the image like it did before.
- When providing an IIIF manifest URL:
  - If the manifest contains a single image, it adds the image based on the image type:
    - If the image is an IIIF image, it adds the IIIF image reference into the workbench.
    - If the image is a plain image, it adds the image to the image server to make it IIIF.
  - If the manifest contains multiple images, it pops up a dialog allowing the user to select an image to add.

**Comment by IanMcCrabb** [comment]
Great
