### ISSUE TITLE
Workbench - Copyright Disclaimer 

### ISSUE THREAD

**Issue by IanMcCrabb** [Systemik-Solutions/glycerine-support#30]
Add link to disclaimer (on site) to registraion UI https://glycerine.io/image-copyright/

**Comment by yangli0516** [comment]
In the registration form, a checkbox with the text:

Accept [image copyright](https://glycerine.io/image-copyright/) disclaimer

**Comment by yangli0516** [comment]
Added the disclaimer in the registration form.

**Comment by IanMcCrabb** [comment]
OK
