### ISSUE TITLE
Site - Viewer Paste Manifest

### ISSUE THREAD

**Issue by IanMcCrabb** [Systemik-Solutions/glycerine-support#41]
Pull a Viewer demo into the foreground. https://demo.viewer.glycerine.io/using-embeds is a lot of clicks away… Enable site visitor to easily submit a manifest

@isobel-andrews design a page for the site so that that users can try out the Viewer themselves with their own manifest.  Mufneg can re-use what Yang has done on  **https://demo.viewer.glycerine.io/using-embeds**  but don't need all the explanation, just paste in a manifest...

@isobel-andrews to design and place a button on the home page to Try Viewer. Perhaps revisit the View Fullscreen button (we don't need it anymore) and put a Try Viewer button below @MufengNiu to implement a page "Try Viewer" based around Yangs Viewer demonstration to allow users to paste in their own manifest. Maybe place this page under Features pull-down?

Not sure where to place the Try Viewer page in the menu.  Maybe we can shift the support page under documentation to make room for it on the menu

**Comment by isobel-andrews** [comment]
https://demo.viewer.glycerine.io/viewer?iiif-content=https://w3id.org/iaw/data/publications/image-sets/01hm598yb6hc3s7btmqth813mg/manifest - link used for iframe

**Comment by isobel-andrews** [comment]
'Try Viewer' page is here: https://glycerine.io/try-viewer/

All @MufengNiu needs to do is implement this section of the demo page on the Try Viewer page:

![Capture](https://github.com/Systemik-Solutions/glycerine-support/assets/29685780/d31c0df5-b5dc-4f89-a5ca-b90419ecffd2)

**Comment by isobel-andrews** [comment]
@MufengNiu If you could do this one ASAP (today if you can) that would be great. Set it up the same way Yang has on the demo page, with the Buddha Triad loaded by default and a paste box above the image, with the two buttons 'View as Embed' and 'Open in Viewer'.

**Comment by MufengNiu** [comment]
@IanMcCrabb  @isobel-andrews 
https://glycerine.io/try-viewer/

**Comment by yangli0516** [comment]
> @IanMcCrabb @isobel-andrews https://glycerine.io/try-viewer/

@MufengNiu, could you encode the manifest URL before appending it to `iiif-content`. It doesn't work with manifest URLs with query strings. e.g. [https://digitalarchive.npm.gov.tw/Antique/setJsonU?uid=48203&Dept=U](https://digitalarchive.npm.gov.tw/Antique/setJsonU?uid=48203&Dept=U)

Also please remove all text above the text input since they are not relevant here.

**Comment by MufengNiu** [comment]
> https://digitalarchive.npm.gov.tw/Antique/setJsonU?uid=48203&Dept=U

Done. Thanks for remind

**Comment by IanMcCrabb** [comment]
Cool
