### ISSUE TITLE
Workbench - Modify Annotation 

### ISSUE THREAD

**Issue by IanMcCrabb** [Systemik-Solutions/glycerine-support#9]
One thing also, when I’ve got the tool for drawing around an object and I make a mistake, I can’t just correct what I’ve done, I have to start again. Frustrating.

**Comment by isobel-andrews** [comment]
Echoed by Adrian and Siobhan as a high-priority issue.

**Comment by yangli0516** [comment]
Added the editing function. Steps of editing an annotation area:

In the editing popup of an annotation, click the edit button in the bottom-left corner:
![image](https://github.com/Systemik-Solutions/glycerine-support/assets/8685304/0e6de6e8-4cf0-4362-ade4-c9b0484afb73)

Adjust the annotation area and click "Finish" to complete:
![image](https://github.com/Systemik-Solutions/glycerine-support/assets/8685304/9c357d0c-2772-4218-a5d5-c1be44191c3f)

Click "Save" to save the annotation:
![image](https://github.com/Systemik-Solutions/glycerine-support/assets/8685304/c399d23a-66ca-41bf-9209-ab1a9f13fd9d)

**Comment by IanMcCrabb** [comment]
Looks great

**Comment by IanMcCrabb** [comment]
@isobel-andrews you might ping Adrian and Jaosn and let the know this is now avaialabe
